apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        name: app1
        image: trialpoc.azurecr.io/mlmodelwithdocker/latest
        resources:
          requests:
            cpu: 1024m
            memory: 100Mi
        ports:
          containerPort: 80
