apiVersion: v1
kind: Service
metadata:
  name: ml-model
  labels:
    app: churnprediction
spec:
  ports:
  - port: 80
    targetPort: python-port
  selector:
    app: churnprediction
  type: LoadBalancer
